package ru.third.inno.task.common.exception;

/**
 * Created by yy on 24.02.17.
 */
public class SubjectDaoException extends Throwable {
}
